### ISSUE TITLE
#validate_audience failing incorrectly when audience doesn't match issuer

### ISSUE THREAD

**Issue by mathildemouw** [onelogin/ruby-saml#283]
We were testing our SAML setup with a response from a client and the ruby-saml response.rb validation on line 456 in #validate_audience failed because the issuer was not one of the audiences.

```
  unless audiences.include? settings.issuer
    error_msg = "#{settings.issuer} is not a valid audience for this Response"
    return append_error(error_msg)
  end
```

It seems like this check is incorrect.  The SAML 2.0 specification says that the Issuer refers to the IDP's entity id and the Audience refers to the SP's entity id (and you can also include any other audiences that the IDP intends for the SAML response, if there are any).  It should be still valid when the issuer is not included in the audiences.

**Comment by pitbulk** [comment]
Understand the settings.issuer as the Service Provider entity ID, not the Issuer attribute of the SAMLResponse.
This was a legacy name, if you review the rest of our toolkits, all uses settings_sp_entityid to define this value, and you can see that all have the same checker:

https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/response.py#L140
https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Response.php#L185

**Comment by mathildemouw** [comment]
@pitbulk Thanks for the response.  I made a pull request with our solution in case it can be of some use, but now that I have seen your reply it seems like it won't be merge-able without compatibility issues. :/

**Comment by raphaelcm** [comment]
Hey guys, this issue makes it so ruby-saml doesn't work with most other mainstream SAML IdPs (Okta, Bitium, Azure, etc).

The PR from @mathildemouw resolves the issue. Would be great if this gem could get back into compliance with the SAML 2.0 specification. Is that on the roadmap at all?

**Comment by pitbulk** [comment]
@raphaelcm  This gem is compliance with the SAML 2.0 specification.

I agree that "sp_entity_id" name is better than the "issuer" name, but I need to keep this name in order to maintain compatibility with deployed ruby-saml toolkit instances. 
Please don't misunderstand this setting parameter that refers always to the "sp_entity_id", don't believe that the "issuer" is the "idp_entity_id".

Issuer is who send the SAML message, in the case of SAMLResponse the Issuer is the "idp_entity_id" but in a AuthNRequest, the Issuer is the "sp_entity_id".

**Comment by tmertens** [comment]
@pitbulk Why not just alias the method and deprecate the old one?

**Comment by pitbulk** [comment]
That should work.
