### ISSUE TITLE
Deeplinking - authorization

### ISSUE THREAD

**Issue by rgerbranda** [onelogin/ruby-saml#361]
I'm looking for instructions about deeplinking.

Example: a user opens a specific page, like https://our.domain/contacts, but is not authorised yet.

After authorization, I would like to redirect the browser to this specific page.
Is it possible to add this URL to the SAML parameters?

**Comment by pitbulk** [comment]
At SAML the RelayState parameter is used to save the "state" of the SP before initiate the SAML flow in order to be able to recover the state once the SAML flow ends.

At ruby-saml you can generate the Authrequest with a ['RelayState' parameter](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/authrequest.rb#L51)
LogoutRequest acept the same ['RelayState' parameter](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/logoutrequest.rb#L71).

You can see an example of its use [here](https://github.com/onelogin/ruby-saml#single-log-out)
