### ISSUE TITLE
Can't verify CSRF token authenticity

### ISSUE THREAD

**Issue by kapil-kk** [onelogin/ruby-saml#387]
Doing ruby-saml integration with okta. All things executed successfully in which, I am getting the SAMLResponse from okta after successfully login with okta and when I redirect it to any routes I see this message in the server log "**can't verify CSRF token authenticity**" and  "**Invalid Authenticity token in HelloWorldController#Index"** in browser.

What I am missing here can someone help please? Thanks!

**Comment by pitbulk** [comment]
It seems your ruby app has CSRF token protection so when the IdP sends the SAMLResponse to the Assertion Consumer Service endpoint of your app, since there is no CSRF token included in the POST you get that error.

You will need to whitelist the SAML endpoints to not require CSRF token (SAML has its own mechanism to maintain the integrity of the message, so CSRF protection is not required on those views).

See related:
- https://github.com/apokalipto/devise_saml_authenticatable/issues/62#issuecomment-249935690
- http://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection.html

**Comment by kapil-kk** [comment]
@pitbulk I tried the solution provided by you but It does not work.

**Comment by pitbulk** [comment]
That error does not belong ruby-saml, instead the ruby web framework that you are using.

You need to deactivate CSRF protection on SAML endpoints. I don't know how your app is, what framework you are using.. so can't help more than what I already provided to you, sorry.

**Comment by kapil-kk** [comment]
@pitbulk - thanks for the quick reply. Can you please confirm why my response is not valid. when I am going to check response.is_valid? it always return false.

**Comment by rqbanerjee** [comment]
This is how I got my application controller to not validate CSRF for init and consume, the two methods i implemented in my saml_controller.rb:

```
class ApplicationController < ActionController::Base
  protect_from_forgery except: [:init, :consume], with: :exception

```
