### ISSUE TITLE
Execute validate_signed_elements only if signed assertion is expected

### ISSUE THREAD

**Issue by tngan** [onelogin/ruby-saml#395]
When `omniauth-saml` handles the response (https://github.com/omniauth/omniauth-saml/blob/master/lib/omniauth/strategies/saml.rb#L134), it would carry out the response validation `validate_signed_elements` no matter the assertion is signed or not (`WantAssertionSigned` in SP's metadata). 

If the assertion is not signed, the following code will throw error because `signature_nodes` and `signed_elements` are empty. [Line 548-550 in response.rb](https://github.com/onelogin/ruby-saml/blob/15fb4789f8cd119fdbd722d58c659129d23a256d/lib/onelogin/ruby-saml/response.rb#L548-L550)

```ruby
unless signature_nodes.length < 3 && !signed_elements.empty?
      return append_error("Found an unexpected number of Signature Element. SAML Response rejected")
end
```

I am not sure if the logic should be introduced here. Is it good to relax the condition here, allowing `signature_nodes` and `signed_elements` to be empty ? 

--- Edited ---

My fault, allowing it to be empty is not a good workaround, how about make this validation method optional, only execute when WantAssertionSigned is set to true.

**Comment by pitbulk** [comment]
See https://github.com/onelogin/python-saml/issues/193#issuecomment-300496562

**Comment by tngan** [comment]
@pitbulk Thanks for your clarification, so in general, if the `WantAssertionSigned` is set to false, does it mean the SP prefers to do signing on the entire response ?

**Comment by pitbulk** [comment]
Value of  [want_assertions_signed](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/settings.rb#L158) on the settings are used on [SP metadata](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/metadata.rb#L32) to indicate to the IdP if the assertion should be signed or not.

SAML standard requires at least the Assertion or the whole message to be signed, otherwise, if there is no Signature, there is no way to verify that the IdP generated the message, that why you get the "Found an unexpected number of Signature Element. SAML Response rejected"

**Comment by tngan** [comment]
I received a SP metadata indicating `WantAssertionSigned` to be false so I felt a bit of confusing. Thanks for your help, I will close this issue as well.
