### ISSUE TITLE
1.4.2 -> 1.4.3 Update - A valid SubjectConfirmation was not found on this Response

### ISSUE THREAD

**Issue by bahudso** [onelogin/ruby-saml#399]
After updating to 1.4.3 our SAML system began reporting the `a valid SubjectConfirmation was not found on this Response` for any SAML response we received.

After reverting to 1.4.2 we no longer receive that error message.

Very odd for a bug patch, eh?

**Comment by pitbulk** [comment]
Must be related with that PR:
https://github.com/onelogin/ruby-saml/pull/397

On 1.4.3 we validate the Recipient of the SubjectConfirmation.

Add the [skip_recipient_check](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/response.rb#L741) as an option when you [initialize the Response](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/response.rb#L40)

**Comment by asaaki** [comment]
Technically speaking an breaking change was introduced.
According to SemVer this should have been even a major level bump (2.0.0).
(The change was not backwards compatible in regards to that I have to opt out of the new behaviour instead of opting in.)

Anyway, we can agree on that this change was not just a bugfix.

**Comment by jhubert** [comment]
We just ran into this as well. When following SemVar, we don't apply a lot of scrutiny to patch bumps. Our fault, I suppose.

I agree that this would definitely be on the major bump side. My recommendation for next time would be to have it introduced with `skip_recipient_check` defaulting to true and then release a 2.0.0 with the default swapped to false.

**Comment by slalomandrew** [comment]
Hey, I've just run into this as well (maybe a version bump in omniauth-saml, which I'm using?). Where should I add the skip_recipient_check option if I'm creating a SAML callback in a Devise-omniauth controller?

**Comment by dvfabbri** [comment]
@slalomandrew Finding the same issue as well. Where is skip_recipient_check added?

**Comment by pitbulk** [comment]
https://github.com/onelogin/ruby-saml#updating-from-142-to-143

**Comment by slalomandrew** [comment]
@pitbulk not as helpful when this is happening in a gem that depends on ruby-saml; not sure if there's a way to force their gem to drop its dependency from 142 to 143.

**Comment by pitbulk** [comment]
Since that is reported by many ppl, I will release a 1.4.4 with that skip skip_recipient_check by default.

But 1.5.0 will have that functionality, so you may open issues on those gem and ask to support what is required  in order to be able to check the destination.

This gem try to be as much secure as possible, that why we keep improving code and adding checks that the SAML standard required and were missed.

**Comment by pitbulk** [comment]
Noticed that release 1.4.4 will do anything based on how main projects adds ruby-saml as dependency.

There are issues opened on devise and [omniauth](https://github.com/omniauth/omniauth-saml/issues/146) and [devise](https://github.com/apokalipto/devise_saml_authenticatable/issues/100)

When I released the new version, I had no notice that  there are projects that does not require to set the acs url... but we may force to add that value in order to be able to make that security check.

**Comment by chrisnicola** [comment]
@pitbulk I think the point everyone is making here is that these are patch and point releases and should not include breaking changes. By updating the version change should have been to 2.0.0 to communicate to people updating ruby-saml that they should check for breaking changes and update their code.
