### ISSUE TITLE
Debugging Invalid Signature on SAML Response

### ISSUE THREAD

**Issue by codeodor** [onelogin/ruby-saml#442]
Hi,

Do you have any tips for debugging this error message? 

> Invalid Signature on SAML Response

We're getting that while using Google as the IDP, and I find it hard to believe Google is the issue here, especially, since we have multiple other Google apps for domains accounts as IDPs that work just fine.

So basically, I think it's a setting somewhere, but we have already started from scratch twice, using what we believe to be the same setup process as the ones we know are working, so I really could use some help on where to look for the issue, or what kinds of things to look at.

Thanks!

**Comment by pitbulk** [comment]
The [errors](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/response.rb#L44) attribute of the response object contain the cause of the invalidation.

In this case you have a "Invalid Signature on SAML Response" that means that the ruby-saml toolkit was not able to verify the signature of the SAMLResponse with the IdP public certificate registered on the toolkit.

In order to fix it, Install [SAMLTracer](https://addons.mozilla.org/es/firefox/addon/saml-tracer/) or [Chrome SAML](https://chrome.google.com/webstore/detail/saml-chrome-panel/paijfdbeoenhembfhkhllainmocckace), or simply set a breakpoint on your code to record the SAMLResponse you get from google. Inside you will find a X509Certificate element, you may verify that its value matches the [idp_cert](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/settings.rb#L28) value.

**Comment by codeodor** [comment]
Thank you. I got a response as you mentioned, and used XMLSec as [detailed on this stackoverflow answer](https://stackoverflow.com/a/28016070/28451) to try to validate the signature.

The signature did not validate. 

Then I noticed that there were two certificates in the IdP metadata for this account that was not working, whereas the ones we did have working only had one. 

That led me to try with only one of the two, which did not work, but when I tried with the second of the two, it did work.  Then I tried with both, but with the order reversed, and I could validate it both with XMLSec and with ruby-saml.

I am not sure why there was a difference, and I do not know why Google outputs the certs in an order that neither XMLSec nor ruby-saml can use to verify the signature, but reversing the order of the certs in the IdP metadata worked to solve my issue.

Thank you a ton for the tips!  Knowing about these tools will make it a lot easier to debug these issues in the future.

**Comment by rqbanerjee** [comment]
I found that both of these settings were necessary. This is the current finger print for okta:
```
settings.idp_cert_fingerprint           = "C6:6B:09:1B:0B:73:03:BC:C1:A5:65:38:75:C3:6C:E4:B3:F0:40:3C:26:E2:E2:EE:7E:EF:18:CB:C5:56:EC:6D"
    settings.idp_cert_fingerprint_algorithm = "http://www.w3.org/2000/09/xmldsig#sha256"
    
```

**Comment by truongnmt** [comment]
> Inside you will find a X509Certificate element, you may verify that its value matches the idp_cert value.

> Then I noticed that there were two certificates in the IdP metadata for this account that was not working

Thanks a lot for your hint!!!! This help me a lot when debugging error!
I got the same error when SAML Response from Google return Invalid Signature error!
