### ISSUE TITLE
1.12.2 has hidden dependencies

### ISSUE THREAD

**Issue by bradw2k** [onelogin/ruby-saml#588]
bundle with 1.12.2 specified in Gemfile is giving:
```
#19 172.1 Fetching ruby-saml 1.12.2
#19 172.3 Downloading ruby-saml-1.12.2 revealed dependencies not in the API or the
#19 172.3 lockfile (nokogiri (>= 1.10.5), rexml (>= 0)).
#19 172.3 Either installing with `--full-index` or running `bundle update ruby-saml`
#19 172.3 should fix the problem.
```
But bundle with 1.12.1 specified in Gemfile works fine!

**Comment by johnnyshields** [comment]
@bradw2k here is the diff between 1.12.1 and 1.12.2:

https://github.com/onelogin/ruby-saml/compare/v1.12.1...v1.12.2

It doesn't look like any of the gem dependencies changed. It's possible this is due to changes in bundler behavior, see this page:

https://makandracards.com/makandra/51932-bundler-error-downloading-gem-revealed-dependencies-not-in-the-api

I think this ticket should probably be closed as there's no evidence that a change in ruby-saml introduced it. @pitbulk

**Comment by Brad-FDI** [comment]
It appears the dependencies added by the calls to `add_runtime_dependency` in `ruby-saml.gemspec` are getting flagged by bundler. Since there's if-logic based on the Ruby version, my guess is there's no way to get around these being runtime dependencies, that's why they were done this way and it cannot be changed. Just a thought.
